name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: "Test projects, ${{ matrix.os.name }}"
    runs-on: ${{ matrix.os.id }}
    strategy:
      matrix:
        os:
          - id: windows-latest
            name: Windows
          - id: ubuntu-latest
            name: Ubuntu

    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Solution
        run: dotnet build -c Debug

      - name: Test Projects
        run: dotnet test -c Debug --no-build
