name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: "Test projects, ${{ matrix.os.name }}"
    runs-on: ${{ matrix.os.id }}
    strategy:
      matrix:
        os:
          - id: windows-latest
            name: Windows
          - id: ubuntu-latest
            name: Ubuntu
          - id: ubuntu-24.04-arm
            name: Ubuntu (ARM64)

    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (Debug)
        run: dotnet build -c Debug

      - name: Build (Release)
        run: dotnet build -c Release

      - name: Test (Debug)
        run: dotnet test -c Debug --no-build --verbosity detailed

      - name: Test (Release)
        run: dotnet test -c Release --no-build --verbosity detailed

      - name: Test (Release, AVX2=0)
        env:
          DOTNET_EnableAVX2: "0"
        run: dotnet test -c Release --no-build

      - name: Test (Release, HWIntrinsic=0)
        env:
          DOTNET_EnableHWIntrinsic: "0"
        run: dotnet test -c Release --no-build
